[package]
name = "reqwest-retry"
version = "0.2.2"
authors = ["Rodrigo Gryzinski <rodrigo.gryzinski@truelayer.com>"]
edition = "2018"
description = "Retry middleware for reqwest."
repository = "https://github.com/TrueLayer/reqwest-middleware"
license = "MIT OR Apache-2.0"
keywords = ["reqwest", "http", "middleware", "retry"]
categories = ["web-programming::http-client"]

[dependencies]
reqwest-middleware = { version = "0.2.0", path = "../reqwest-middleware" }

anyhow = "1"
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["clock"], default-features = false }
futures = "0.3"
http = "0.2"
reqwest = { version = "0.11", default-features = false }
retry-policies = "0.1"
task-local-extensions = "0.1.4"
tracing = "0.1.26"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper = "0.14"
tokio = { version = "1.6", features = ["time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
parking_lot = { version = "0.11.2", features = ["wasm-bindgen"] } # work around https://github.com/tomaka/wasm-timer/issues/14
wasm-timer = "0.2.5"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
paste = "1"
tokio = { version = "1", features = ["full"] }
wiremock = "0.5"
futures = "0.3"
